### ISSUE TITLE
Zbyt wolne zmiany xD

### ISSUE THREAD

**Issue by squizee** [itlibrium/DDD-starter-dotnet#1]
Czekamy i czekamy a tu nic się nie dzieje? :) Co jaki czas można spodziewać się nowych wpisów? :)

**Comment by szjanikowski** [comment]
Hej, super, że się odzywacie, to zawsze daje motywacyjnego kopa ;) W tym tygodniu wjadą polityki :) W wakacje też będziemy coś dorzucać, ale nie damy się pokroić za regularność. Ostateczny szlif pewnie jesienią.

**Comment by technites-pl** [comment]
Dodaliśmy implementację Polityk: https://github.com/itlibrium/DDD-starter-dotnet/tree/master/Sales/Sales.Domain/Pricing
Na naszym blogu jest też artykuł na ten temat: https://itlibrium.com/polityki-z-ddd-w-csharp/

W tym tygodniu pojawi się jeszcze implementacja Fabryki Polityk.

**Comment by mpyclikcorp** [comment]
Halo halo, nie śpimy, programujemy :D :D
